FROM ubuntu:20.04

RUN apt-get update && apt-get install -y \
    build-essential \
    net-tools \
    iputils-ping \
    iproute2 \
    xinetd \
    telnetd \
    iptables \
    uml-utilities \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY vpn/vpn-setup-server.sh /app/vpn-setup-server.sh
RUN chmod +x /app/vpn-setup-server.sh

CMD ["tail", "-f", "/dev/null"]