version: '3'

services:
  host_u:
    build:
      context: .
      dockerfile: Dockerfile.host
    container_name: host_u
    networks:
      nat_network:
        ipv4_address: 10.0.2.7
    cap_add:
      - NET_ADMIN
    volumes:
      - ./vpn:/app/vpn

  host_v:
    build:
      context: .
      dockerfile: Dockerfile.host
    container_name: host_v
    networks:
      internal_network:
        ipv4_address: 192.168.60.101
    cap_add:
      - NET_ADMIN

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    container_name: gateway
    networks:
      nat_network:
        ipv4_address: 10.0.2.8
      internal_network:
        ipv4_address: 192.168.60.1
    cap_add:
      - NET_ADMIN
    volumes:
      - ./vpn:/app/vpn

networks:
  nat_network:
    ipam:
      config:
        - subnet: 10.0.2.0/24
  internal_network:
    ipam:
      config:
        - subnet: 192.168.60.0/24
